language: ruby
sudo: false
addons:
  postgresql: "9.6"
services:
  - postgresql
cache: bundler
before_install:
  - gem install bundler
script:
  - bundle exec rubocop
  - bundle exec rspec
matrix:
  fast_finish: true
  include:
    - rvm: 2.3.7
    - rvm: 2.4.4
    - rvm: 2.5.1
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
